import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Fonts
import { Inter, Urbanist } from "next/font/google";
import Navbar from "@/components/Navbar";
import { CoinProvider } from "./providers/coinProvider";
import { BackgroundGradientAnimation } from "@/components/ui/background-gradient-animation";
import { BubbleBackground } from "@/components/animate-ui/components/backgrounds/bubble";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Define a CSS variable name
  display: "swap",
});

const urbanist = Urbanist({
  // Use underscore for multi-word font names
  subsets: ["latin"],
  variable: "--font-urbanist",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overscroll-none">
      <body
        className={`${inter.variable} ${urbanist.variable} antialiased dark`}
      >
        <CoinProvider>
          <Navbar />

          {children}
          <Footer />
        </CoinProvider>
      </body>
    </html>
  );
}
